version: 2
updates:
  # Enable version updates for rust
  - package-ecosystem: "rust:cargo"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
