[package]
name = "aoc_1906"
version = "0.1.0"
authors = ["Jake Merdich <Jake.Merdich@amd.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vec-tree = "0.1.2"
permutohedron = "0.2.4"