[package]
name = "aoc_1911"
version = "0.1.0"
authors = ["Jake Merdich <jake@merdich.com>"]
edition = "2018"

[dependencies]
intcode = { path = "../../common/intcode" }
arbgrid = { path = "../../common/arbgrid" }
