[package]
name = "aoc_1909"
version = "0.1.0"
authors = ["Jake Merdich <jake@merdich.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intcode = { path = "../../common/intcode" }
